"""Public split-stage inverse coverage for cached flex equality coefficients."""
import os

import mujoco
import numpy as np
import pytest


def _host(value):
  return value.detach().cpu().numpy()


def _flex_model(kind):
  if kind == "flexvert":
    xml = '''<mujoco>
      <option timestep=".002" gravity="0 0 0" integrator="Euler"
              solver="PGS" iterations="50"/>
      <worldbody><flexcomp name="cloth" type="grid" count="2 2 1"
          spacing=".1 .1 .1" mass="1" radius=".01" dim="2">
        <edge equality="strain"/>
        <contact contype="0" conaffinity="0"/>
      </flexcomp></worldbody>
      <equality><flexvert flex="cloth" solref=".03 1.2"
          solimp=".8 .95 .01 .5 2"/></equality>
    </mujoco>'''
  elif kind == "flexstrain":
    xml = '''<mujoco>
      <option timestep=".002" gravity="0 0 0" integrator="Euler"
              solver="PGS" iterations="50"/>
      <worldbody><body name="root"><freejoint/>
        <geom type="sphere" size=".02" mass="1"/>
        <flexcomp name="volume" type="grid" count="3 2 2"
            cellcount="2 1 1" spacing=".1 .1 .1" mass="1" dim="3"
            dof="trilinear">
          <edge equality="strain" solref=".03 1.2"
              solimp=".8 .95 .01 .5 2"/>
          <contact contype="0" conaffinity="0" selfcollide="none"/>
        </flexcomp>
      </body></worldbody>
    </mujoco>'''
  else:
    raise ValueError(kind)
  model = mujoco.MjModel.from_xml_string(xml)
  model.opt.enableflags |= int(mujoco.mjtEnableBit.mjENBL_INVDISCRETE)
  return model


@pytest.mark.parametrize("kind", ["flexvert", "flexstrain"])
def test_cpu_flex_equality_cached_velocity_uses_source_b_impedance_formula(kind):
  """Prove the fixture's split-VEL CPU oracle has raw source B semantics."""
  model = _flex_model(kind)
  qpos = np.asarray(model.qpos0, dtype=np.float64).copy()
  if kind == "flexvert":
    qpos += np.linspace(-.003, .004, model.nq)
  else:
    qpos[:3] += np.asarray([.003, -.002, .004])
    qpos[7:] += np.linspace(-.002, .003, model.nq - 7)
  qvel = np.linspace(-.09, .07, model.nv)
  changed = qvel + np.linspace(.013, -.009, model.nv)
  data = mujoco.MjData(model)
  data.qpos[:], data.qvel[:] = qpos, qvel
  mujoco.mj_forward(model, data)
  equality_type = (mujoco.mjtEq.mjEQ_FLEXVERT if kind == "flexvert"
                   else mujoco.mjtEq.mjEQ_FLEXSTRAIN)
  eqids = np.flatnonzero(np.asarray(model.eq_type) == int(equality_type))
  assert eqids.size
  rows = np.flatnonzero(
      (data.efc_type == int(mujoco.mjtConstraint.mjCNSTR_EQUALITY))
      & np.isin(data.efc_id, eqids))
  assert rows.size > 0
  pos_before = data.efc_pos[rows].copy()
  R_before = data.efc_R[rows].copy()
  aref_before = data.efc_aref[rows].copy()
  row_eqids = data.efc_id[rows].copy()
  delta_velocity = changed - qvel
  velocity_delta = np.zeros(data.nefc, dtype=np.float64)
  mujoco.mj_mulJacVec(model, data, velocity_delta, delta_velocity)
  data.qvel[:] = changed
  mujoco.mj_forwardSkip(model, data, mujoco.mjtStage.mjSTAGE_POS, 0)
  np.testing.assert_array_equal(data.efc_pos[rows], pos_before)
  np.testing.assert_array_equal(data.efc_R[rows], R_before)
  for eqid in eqids:
    selected = row_eqids == int(eqid)
    if not np.any(selected):
      continue
    ref = np.asarray(model.eq_solref[eqid], dtype=np.float64)
    dmax = float(model.eq_solimp[eqid, 1])
    b0 = (2.0 / (dmax * max(ref[0], 2.0 * float(model.opt.timestep)))
          if ref[1] > 0.0 else -ref[1] / dmax)
    np.testing.assert_allclose(
        data.efc_aref[rows[selected]] - aref_before[selected],
        -b0 * velocity_delta[rows[selected]], rtol=3e-6, atol=3e-8)
  assert np.max(np.abs(data.efc_aref[rows] - aref_before)) > 1e-5


def test_cpu_flex_coefficient_broadcast_preserves_raw_values():
  """Scalar FLEXVERT/STRAIN and per-row FLEX inputs share one ABI."""
  torch = pytest.importorskip("torch")
  from mujoco_metal.coupled_constraints import (
      _expand_flex_equality_reference_coefficients)

  impedance = torch.full((2, 3), .73, dtype=torch.float32)
  for k0, b0 in ((12.5, 4.25), (np.float32(12.5), np.float32(4.25)),
                 (torch.tensor(12.5), torch.tensor(4.25))):
    k_rows, b_rows = _expand_flex_equality_reference_coefficients(
        k0, b0, impedance)
    torch.testing.assert_close(k_rows, torch.full_like(impedance, 12.5))
    torch.testing.assert_close(b_rows, torch.full_like(impedance, 4.25))
  per_row_k = torch.arange(6, dtype=torch.float32).reshape(2, 3)
  per_row_b = per_row_k + 10
  k_rows, b_rows = _expand_flex_equality_reference_coefficients(
      per_row_k, per_row_b, impedance)
  torch.testing.assert_close(k_rows, per_row_k)
  torch.testing.assert_close(b_rows, per_row_b)


def test_cpu_flexvert_fixture_retains_zero_row_autostrain_without_solver_rows():
  """Autogenerated zero-mode strain equality is catalogued but not dispatched."""
  from mujoco_metal.coupled_constraints import lower_coupled_constraints

  model = _flex_model("flexvert")
  descriptor = lower_coupled_constraints(model)
  flexvert = int(mujoco.mjtEq.mjEQ_FLEXVERT)
  flexstrain = int(mujoco.mjtEq.mjEQ_FLEXSTRAIN)
  zero_row_strain = [eid for eid, kind in enumerate(model.eq_type)
                     if int(kind) == flexstrain]
  assert zero_row_strain
  assert any(int(kind) == flexvert for kind in model.eq_type)
  assert all(int(descriptor.eq_rownum[eid]) == 0 for eid in zero_row_strain)


@pytest.mark.gpu
@pytest.mark.skipif(os.getenv("MUJOCO_METAL_RUN_GPU") != "1",
                    reason="native flex inverse requires explicit GPU opt-in")
@pytest.mark.parametrize("kind", ["flexvert", "flexstrain"])
@pytest.mark.parametrize("jacobian", ["dense", "sparse"])
def test_public_flex_equalities_full_and_split_inverse_match_pinned_cpu(kind, jacobian):
  """Cover FLEXVERT/FLEXSTRAIN through packed POS-context to cached VEL."""
  import torch
  from mujoco_metal import MetalSimulation
  from mujoco_metal.native_api import mj_fwdPosition, mj_inverse, mj_inverseSkip

  model = _flex_model(kind)
  # The scalable profile supports these flex topologies in both Jacobian
  # layouts; the Euler profile intentionally has a smaller dense nv admission.
  profile = "integrated_scalable_v1"
  model.opt.jacobian = (mujoco.mjtJacobian.mjJAC_SPARSE
                        if jacobian == "sparse"
                        else mujoco.mjtJacobian.mjJAC_DENSE)
  qpos = np.asarray(model.qpos0, dtype=np.float32).copy()
  if kind == "flexvert":
    qpos += np.linspace(-.003, .004, model.nq, dtype=np.float32)
  else:
    qpos[:3] += np.asarray([.003, -.002, .004], dtype=np.float32)
    qpos[7:] += np.linspace(-.002, .003, model.nq - 7, dtype=np.float32)
  qvel = np.linspace(-.09, .07, model.nv, dtype=np.float32)
  sim = MetalSimulation(model, batch_size=1, qpos=qpos[None, :],
                        qvel=qvel[None, :], profile=profile)
  expected_mode = 1 if jacobian == "sparse" else 0
  assert sim._coupled_constraints._jacobian_layout.mode == expected_mode

  cpu_roll = mujoco.MjData(model)
  cpu_roll.qpos[:] = qpos
  cpu_roll.qvel[:] = qvel
  for _ in range(2):
    status = sim.step()
    assert not status.detach().cpu().numpy().any()
    mujoco.mj_step(model, cpu_roll)
  native_qpos = _host(sim.state._qpos)[0]
  native_qvel = _host(sim.state._qvel)[0]
  target = cpu_roll.qacc.astype(np.float32).astype(np.float64)
  qacc_input = torch.as_tensor(target[None, :], dtype=torch.float32,
                               device="mps")

  # Fresh inverse at exact native state, compared with source CPU at the
  # exact represented acceleration target.
  fresh = _host(mj_inverse(sim, qacc=qacc_input))[0]
  cpu = mujoco.MjData(model)
  cpu.qpos[:] = native_qpos
  cpu.qvel[:] = native_qvel
  cpu.qacc[:] = target
  mujoco.mj_inverse(model, cpu)
  np.testing.assert_allclose(fresh, cpu.qfrc_inverse, atol=8e-3, rtol=8e-3,
      err_msg=f"fresh {kind} inverse ({profile})")

  # Rebuild only POS, then query a distinct VEL. The changed velocity makes
  # B*J*qvel observable while the retained position/impedance remains fixed.
  pos_record = mj_fwdPosition(sim, return_record=True, skipsensor=True)
  query_qvel = native_qvel + np.linspace(.013, -.009, model.nv,
                                         dtype=np.float32)
  query_qvel_t = torch.as_tensor(query_qvel[None, :], dtype=torch.float32,
                                 device="mps")
  split = _host(mj_inverseSkip(
      sim, skipstage=mujoco.mjtStage.mjSTAGE_POS, record=pos_record,
      qvel=query_qvel_t, qacc=qacc_input))[0]
  cpu_split = mujoco.MjData(model)
  cpu_split.qpos[:] = native_qpos
  cpu_split.qvel[:] = query_qvel.astype(np.float64)
  cpu_split.qacc[:] = target
  mujoco.mj_inverse(model, cpu_split)
  np.testing.assert_allclose(split, cpu_split.qfrc_inverse,
      atol=8e-3, rtol=8e-3, err_msg=f"split {kind} inverse ({profile})")
  assert np.max(np.abs(cpu_split.qfrc_inverse - cpu.qfrc_inverse)) > 1e-5
